services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV={NODE_ENV}
      - PORT=${PORT}

      - DATABASE_URL=${DATABASE_URL_DOCKER}

      - CLIENT_URL=${CLIENT_URL}

      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_RETURN_URL=${STRIPE_RETURN_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_RETURN_URL=${PAYPAL_RETURN_URL}
      - PAYPAL_CANCEL_URL=${PAYPAL_CANCEL_URL}
      - PAYPAL_BRAND_NAME=${PAYPAL_BRAND_NAME}

      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_UPLOAD_PRESET=${CLOUDINARY_UPLOAD_PRESET}

      - EMAILJS_SERVICE_ID=${EMAILJS_SERVICE_ID}
      - EMAILJS_API_URL=${EMAILJS_API_URL}
      - EMAILJS_PUBLIC_KEY=${EMAILJS_PUBLIC_KEY}
      - EMAILJS_TEMPLATE_ID=${EMAILJS_TEMPLATE_ID}
    depends_on:
      - db
    volumes:
      - /app/node_modules
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomm
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
